name: Test
on: [ push ]
jobs:
  run:
    name: Run Test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Enable corepack
        run: corepack enable

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm format-check

      - name: Test
        run: pnpm test
